### PR TITLE
Add apcu for PHP7

### PR DESCRIPTION
**Pull request by olivier34000**
On php7 apc is changed by apcu

### CODE REVIEW

**Comment by dominikzogg** [comment]
@olivier34000 thank you for your contribution

**Comment by dominikzogg** [comment]
https://github.com/saxulum/saxulum-doctrine-mongodb-odm-provider/releases/tag/2.3.0

**Comment by olivier34000** [comment]
@dominikzogg thank you :+1: You are too fast

**Comment by dominikzogg** [comment]
@olivier34000 you had luck, that i saw it that fast and there was no risk to merge it.
If you need this change for V1 (Silex 1.x) it would be very cool if you would create a PR too.

**Pull request merged**
